# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'G-VEDFVT1M9C'

menu:
- {name: 'Interesting Facts',  url: 'facts'}
- {name: 'Learning Resources', url: 'resources'}
- {name: 'Sample Posts',       url: 'sample-posts'}
- {name: 'Documentation',      url: 'documentation'}
- {name: 'About',              url: 'about'}
- {name: 'Contact',            url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'envelope', link:   'mailto:copelanddevwork@gmail.com'}
- {icon: 'github', link: 'https://github.com/FishheadNate'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}
#- {icon: 'twitter', link:    'https://twitter.com/Fishhead_Nate'}
#- {icon: 'facebook', link:   'https://www.facebook.com/copeland.nathan'}
#- {icon: 'instagram', link:  'https://www.instagram.com/fishhead_nate'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
