# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
#- {name: 'Interesting Facts',  url: 'facts'}
#- {name: 'Learning Resources', url: 'resources'}
#- {name: 'Sample Posts',       url: 'sample-posts'}
- {name: 'Teaching Associate Professor',      url: 'teachingAssociateProfessor'}
- {name: 'DJ',              url: 'dj'}
#- {name: 'Food Remixer',            url: 'foodRemixer'}
- {name: 'Connect with Chris',            url: 'reachOut'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'linkedin', link:    'https://www.linkedin.com/in/christopher-kinson-2b68567a'}
- {icon: 'github', link:   'https://www.github.com/kinson2'}
- {icon: 'mixcloud', link: 'https://www.mixcloud.com/chriskinson_djck/'}
#- {icon: 'facebook', link:   'https://www.facebook.com/paululele'}
#- {icon: 'instagram', link:  'https://instagram.com/paululele'}
#- {icon: 'envelope', link:   'mailto:kinson2@illinois.edu'}
#- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
